### ISSUE TITLE
공지 기능 API 개발

### ISSUE THREAD

**Issue by beom-i** [NKdevelop1/NK_develop_back#32]
<img width="942" alt="스크린샷 2024-03-06 오후 4 12 51" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/5df5f23f-7396-4500-9bf1-285a497ddb03">

- [x] 수업 공지 생성
- [x] 수업 공지 수정
- [x] 수업 공지 삭제
- [x] 전체 수업 공지 조회
- [x] 특정 수업 공지 조회 
-----
- [x] 관리자 공지 생성
- [x] 관리자 공지 수정
- [x] 관리자 공지 삭제
- [x] 전체 관리자 공지 조회
- [x] 특정 관리자 공지 조회 공지 조회

공지의 ERD

<img width="1222" alt="스크린샷 2024-03-06 오전 1 27 45" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/ea9162ec-9ac3-4fc2-908d-4468e7254877">

1) 수업 공지 : path로 부터 각 수업의 id를 받아 각 수업 공지
2) 관리자 공지 : 별도로 공지 존재
로 나뉜다.

누구에게 공지가 공개되는 지는 해당 type에 따라 결정됩니다.
ex) STUDENT_PARENT 값을 받으면 student와 parent만 공지를 볼 수 있습니다.

1) 수업 공지 type 선택지

<img width="346" alt="스크린샷 2024-03-06 오전 1 25 46" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/497cf5ed-5195-45b7-b7fe-4080084bcfab">

2) 관리자 공지 type 선택지

<img width="581" alt="스크린샷 2024-03-06 오전 1 26 01" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/b05a798b-3ded-441e-8f23-974433f6c411">

**Comment by beom-i** [comment]
Notice ERD에 class_id가 외래키로 갖고 있는데 관리자 공지인 경우에는 classroom 을 DB에 id 1로 관리자 전용 클래스룸을 만들어서 그 수업은 전체와 연결되어있는 클래스로 한다면 다른 공지들과 형태도 비슷하고 비슷하게 사용할 수 있지 않을까?

**Comment by beom-i** [comment]
[1] 수업 공지 생성

<img width="1049" alt="스크린샷 2024-03-05 오후 11 01 59" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/3070576c-aeb2-4f10-98d9-2991eb41a345">

[2] 수업 공지 수정

<img width="1056" alt="스크린샷 2024-03-05 오후 11 02 33" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/1802ef22-29bf-4641-884e-4ef9a37aeb89">


[3] 수업 공지 삭제

<img width="1064" alt="스크린샷 2024-03-05 오후 11 02 56" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/55ccc6b3-fbb9-4a40-b4da-d5cf5ae9a77a">

[4] 전체 수업 공지 조회

<img width="1121" alt="스크린샷 2024-03-05 오후 11 03 10" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/1ae47055-4b49-4afb-b119-535abdcf357a">

[5] 특정 수업 공지 조회

<img width="1133" alt="스크린샷 2024-03-05 오후 11 03 26" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/548d51e3-355e-4c46-b68b-e1089cf210ee">

**Comment by beom-i** [comment]
[1] 관리자 공지 생성

<img width="769" alt="스크린샷 2024-03-06 오전 12 13 54" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/3ea3e2d0-95d9-475f-a3ef-ba8627abb6c9">

[2] 관리자 공지 수정

<img width="789" alt="스크린샷 2024-03-06 오전 12 14 02" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/45e0c89c-9598-4418-a01a-5e967b78fb4d">

[3] 관리자 공지 삭제

<img width="801" alt="스크린샷 2024-03-06 오전 12 14 11" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/cc3f853c-23ce-487d-9131-b5c918a6ea78">


[4] 전체 관리자 공지 조회

<img width="892" alt="스크린샷 2024-03-06 오전 12 14 19" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/f855e0bf-1040-43ae-a3cc-55614d69873b">

[5] 특정 관리자 공지 조회

<img width="862" alt="스크린샷 2024-03-06 오전 12 14 27" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/3011897d-06cf-4241-acf2-987130e6e84b">

**Comment by DevTae** [comment]
- 변경된 Classroom 생성에 대한 예시를 첨부합니다.
  ![image](https://github.com/NKdevelop1/NK_develop_back/assets/55177359/9e5685da-4530-48bb-b20b-88255e94ca68)
