### ISSUE TITLE
학생 로그인 시스템 및 API 추가

### ISSUE THREAD

**Issue by beom-i** [NKdevelop1/NK_develop_back#4]
- [x] 학생 계정 생성
- [x] 학생 계정 삭제
- [x] 학생 계정 설정
- [x] 모든 학생 계정 리스트 조회
- [x] 특정 학생 계정 정보 조회
- [ ] 특정 학생의 특정 정보 조회 (나중에 프론트에서 요구되는 사항에 따라 구현 예정 ex. 이 학생의 학교는? 등..)
- [ ] 학생 계정 세부정보 조회 (관리자)
--------
- [x] 학생 계정 로그인
- [x] 학생 계정 토큰 재발급
- [x] 학생 계정 로그아웃
--------
- [x] 등록된 모든 학교 리스트 조회
- [x] 학교 추가
- [x] 학교 삭제
- [x] 학교 DB에 중복 X 제약조건
- [ ] 학교 DB에 ~ 고등학교만 가능하게 제약조건 추가 
-> Pattern Annotation + 정규식 추가해봤는데, Validation 의존성이 잘 안되는 상황
--------
- [x] 학교와 학생 연결 (단방향 or 양방향)
       -> 단방향은 학생이 어떤 학교인 지 볼 수 있는데(외래키 가지니까), 근데 학교에서 어떤 학생이 있는 지 보고 싶다면 양방향을 선택해야함.
       -> 일단은, 요구사항에 없기 때문에 단방향으로 할 생각임, 추후 요구사항이 들어오면 양방향으로 바꿔야함 ([참고](https://velog.io/@seulki412/Spring-Boot-JPA%EB%A1%9C-%EC%97%94%ED%8B%B0%ED%8B%B0-%ED%85%8C%EC%9D%B4%EB%B8%94-%EC%83%9D%EC%84%B1%ED%95%98%EA%B8%B0-PK-FK-%EC%97%B0%EA%B2%B0%ED%95%98%EA%B8%B0))
- [x] 학생을 추가할 때, 등록된 학교가 없거나 id와 id의 학교 이름이 다를 경우 오류 메시지 발생하도록 추가
- [x] 학교와 연결된 학생이 존재할 때 학교를 삭제할 수 없음 or 학교 추가되면 삭제가 절대 불가능 (가능하려면 학교에 연결된 학생 없도록)

**Comment by beom-i** [comment]
1. 학생에 대한 데이터베이스 스키마 정의한다.
2. Java Spring Boot에 적용되게 한다.
3. JPA 테스트

**Comment by beom-i** [comment]
태현님 이슈 피드백 추가) 
->학생 테이블에 휴대폰 번호, 생년월일, 학교(학생), 학년(학생) 을 추가
->학교 추가하려면 학교 테이블 만들어서 관리자에서 특정 학교 추가하면 그것중에 선택할 수 있게 해둬야함 안그러면 각 입력마다 조금씩 다르면 일반화 안될 것 같음 (ex. ~고등학교 VS ~고)

**Comment by beom-i** [comment]
Branch Name : main/develop/StudentDB
커밋할 때 Github Issue 티켓코드 #4 추가하기

**Comment by beom-i** [comment]
spring security, jwt 사용하여 학생 로그인/로그아웃 시스템 구현

**Comment by beom-i** [comment]
API 개발 조금 더 고도화 + 상세 API

**Comment by DevTae** [comment]
> ~태현님 이슈 피드백 추가([#1 (comment)](https://github.com/NKdevelop1/NK_develop_back/issues/1#issuecomment-1875280503)) ->학생 테이블에 휴대폰 번호, 생년월일, 학교(학생), 학년(학생) 을 추가 ->완료~
> 
> ERD) -> 학생 테이블에 학교 추가하려면 학교 테이블 만들어서 관리자에서 특정 학교 추가하면 그것중에 선택할 수 있게 해둬야함 안그러면 각 입력마다 조금씩 다르면 일반화 안될 것 같음 (ex. ~고등학교 VS ~고)

![image](https://github.com/NKdevelop1/NK_develop_back/assets/55177359/3b814304-e539-4b87-b39f-4c63dc36ab86)

위 데이터베이스 ERD 처럼 구성하여 개발하면 될 것 같습니다! 좋은 관점인 것 같아요 👍

**Comment by beom-i** [comment]
[] 선생님 계정 생성
 선생님 계정 삭제
 선생님 계정 설정
 선생님 계정 리스트 조회
 선생님 계정 정보 조회
 선생님 계정 세부정보 조회
 선생님 계정 로그인
 선생님 계정 토큰 재발급
 선생님 계정 로그아웃
 선생님 계정 종속 반 리스트
 선생님 계정 반에 학생 추가
 선생님 계정 반에 학생 제거

**Comment by beom-i** [comment]
JWT 토큰 관련으로는 태현님의 issue 확인 부탁드립니다.

1. 특정 학생 정보 조회
<img width="1085" alt="studentget" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/b639a76e-c8a5-4770-b8b7-6b40807db512">

2. 학생 회원가입 (권한 필요)
<img width="1104" alt="studentpost" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/c6fa1e6e-b163-47e9-a9c8-43e8f4704ca9">


3. 학생 회원삭제 (권한 필요)

<img width="1056" alt="studentdelete" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/5650c98b-f242-427d-a310-fbf5fc23c9e8">

4. 회원 정보 수정
<img width="1068" alt="studentput" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/e03c80f0-4d14-4576-b8f3-c06b233c6a74">


5. 모든 학생 정보 조회
<img width="1026" alt="studentsget" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/21e92d23-4ef7-4768-8d46-8f0ebe93cd98">


--------------------

1. 등록된 모든 학교 조회
<img width="999" alt="schoolget" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/3c8b38bd-b345-407a-9456-2e1901e2f65a">


2. 학교 생성

<img width="925" alt="schoolpost" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/853d2901-f23e-4b29-a82d-5ee232aea93f">



3. 학교 삭제

<img width="1035" alt="schooldelete" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/2436de6d-8317-443a-b7ca-8e38ea2df1b0">

**Comment by beom-i** [comment]
해당 스프린트 종료로 추후 프론트와 연계하여 피드백 요청 받고 개발 예정
