### ISSUE TITLE
검색 및 정렬 기능 API 구현

### ISSUE THREAD

**Issue by DevTae** [NKdevelop1/NK_develop_back#43]
- 3차 스프린트 (4.22~4.30)
  - 검색 알고리즘
    - contain, like 로 할 예정

**Comment by beom-i** [comment]
- [ ] 학생 이름 검색
- [ ] 선생님 이름 검색
- [ ] 반 이름 검색
- [ ] 관리자 공지 검색
- [ ] 수업 공지 검색

**Comment by beom-i** [comment]
1) keyword가 없는 경우 + 페이지 조회
<img width="884" alt="스크린샷 2024-04-30 오후 12 33 05" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/0f29f158-1610-419d-aaa5-25e56626c75d">
<img width="887" alt="스크린샷 2024-04-30 오후 12 33 00" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/ab52ef75-cab9-45c5-aad2-d3eef768a0d7">


2) 키워드를 추가하여 학생 이름 검색
<img width="883" alt="스크린샷 2024-04-30 오후 12 32 56" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/7923a7f5-a4bd-4f91-95fe-a8314bca0c72">

**Comment by beom-i** [comment]
2-1) 선생님 이름 검색 (keyword가 없는 경우 + 페이지 조회)
<img width="891" alt="스크린샷 2024-04-30 오후 1 32 24" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/77daf87a-2889-4337-94f6-8bf0cf193f2e">
<img width="876" alt="스크린샷 2024-04-30 오후 1 32 31" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/b762fa57-7175-476c-8d85-3d0a3e01e033">

2-2) 선생님 이름 검색 (keyword가 있는 경우)
<img width="886" alt="스크린샷 2024-04-30 오후 1 32 18" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/daf08589-ee5c-4ab6-95c8-e5e177bd238a">

**Comment by beom-i** [comment]
3-1) 수업 이름 검색 (keyword가 없는 경우 + 페이지 조회)

<img width="908" alt="스크린샷 2024-04-30 오전 11 57 57" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/bfb57d1c-363f-465a-9a7b-66b5968963d8">

<img width="929" alt="스크린샷 2024-04-30 오전 11 58 04" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/dc18c46f-854a-44c3-8ce1-7e4a763086cf">

3-2) 수업 이름 검색 (keyword가 있는 경우)

<img width="928" alt="스크린샷 2024-04-30 오전 11 57 52" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/df7830e3-da43-4ed5-8f84-85c5f0222ce7">

**Comment by beom-i** [comment]
4-1) 관리자 공지 검색 (기본)

<img width="947" alt="스크린샷 2024-04-30 오후 11 36 20" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/92c78e0b-e209-4510-afe3-6fadc36949da">

4-2) 관리자 공지 검색 (기본 + type 추가)

<img width="952" alt="스크린샷 2024-04-30 오후 11 36 30" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/6b99c6e3-3e3b-4603-9ed5-5d210e0e6605">

4-3) 관리자 공지 검색 (기본 + type 다중 추가)

<img width="949" alt="스크린샷 2024-04-30 오후 11 38 12" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/2da60743-de18-4653-bebd-6fc53002c100">


4-4) 관리자 공지 검색 (기본 + type 다중 추가 + keyword 추가)

<img width="952" alt="스크린샷 2024-04-30 오후 11 38 25" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/52509936-661c-4067-b36d-7971cc05cd26">

**Comment by beom-i** [comment]
5-1) 수업 공지 검색 (기본)

<img width="949" alt="스크린샷 2024-04-30 오후 11 34 49" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/329df9cd-ef80-4ec5-98bb-287e2ab4c663">

5-2) 수업 공지 검색 (기본 + type 추가)

<img width="945" alt="스크린샷 2024-04-30 오후 11 35 27" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/d48836fc-4dc7-40f4-8389-74eb8de2ccdf">

5-3) 수업 공지 검색 (기본 + type 다중 추가)

<img width="962" alt="스크린샷 2024-04-30 오후 11 35 38" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/88a0f624-9993-4d1d-acd1-e3b3db60d3ab">


5-4) 수업 공지 검색 (기본 + type 다중 추가 + keyword 추가)

<img width="951" alt="스크린샷 2024-04-30 오후 11 35 54" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/727579c4-83c4-4d5f-8029-8a09c7735ea6">
