### ISSUE TITLE
3차 프론트엔드 API 피드백 반영

### ISSUE THREAD

**Issue by DevTae** [NKdevelop1/NK_develop_back#54]
- [x] JWT 유효기간 재설정
  - access token : 1일
  - refresh token : 30일
- [x] pageable current page 1 부터 시작하도록 수정

**Comment by Dragonite-Lee** [comment]
- [ ] 학교 관리 삭제 건 : 다중삭제 기능이 제외됨 (기능 추가 바람)

**Comment by Dragonite-Lee** [comment]
- [ ] 학생 / 학부모 / 선생 에러코드 메시지 

- [ ] 각 토큰 유효기간 (태현님이 처리하신다고 함)
- [ ] 학생 / 학부모 / 선생 get요청 비밀번호에 대한 건 (논의 필요)

**Comment by beom-i** [comment]
- [ ] 학생/학부모/선생님/학교 다중 삭제
- [ ] 학교/학부모/선생님 회원가입 시, 이름 존재 & active=false인 경우 true로 바꾸기

**Comment by Dragonite-Lee** [comment]
- [ ] 에러 메시지 관련 추가사항-> 만약 데이터를 다 안 입력하면 그에 해당하는 메시지도 오나요? ex) 아이디를 입력하지 않았습니다. 학년을 입력하지 않았습니다.

**Comment by Dragonite-Lee** [comment]
- [ ] /api/parent 의 api에 birth는 제외해주셔도 될 것 같습니다.

**Comment by beom-i** [comment]
- [ ] 학교 id로 주키 변경
- [ ] 학교-학생-학부모-선생 다중삭제
- [ ] 에러 메시지 (태현 - 숙제/학부모/로그인, 예범- 선생/학생/수업/공지)

**Comment by DevTae** [comment]
- [Update codes to catch exception on insertion and modifying of parent and homework]
(https://github.com/NKdevelop1/NK_develop_back/commit/e7e4388d2a101848b1e13f1c8c9ff419307480b0)

- [Update serviceImpl codes to catch exception on insertion and modifying of parent and homework]
(https://github.com/NKdevelop1/NK_develop_back/commit/f08d5e36e6d3411af5de61b3f1fe42462dfc0d16)
