### ISSUE TITLE
선생님 로그인 기능 및 기본 API 정의

### ISSUE THREAD

**Issue by hyunwook7120** [NKdevelop1/NK_develop_back#7]
- [x] 선생님 계정 생성
- [x] 선생님 계정 삭제
- [x] 선생님 계정 설정
- [x] 선생님 계정 리스트 조회
- [x] 선생님 계정 정보 조회
- [x] 선생님 계정 세부정보 조회
- [x] 선생님 계정 로그인
- [x] 선생님 계정 토큰 재발급
- [x] 선생님 계정 로그아웃
- [x] 선생님 계정 종속 반 리스트
- [x] 선생님 계정 반에 학생 추가
- [x] 선생님 계정 반에 학생 제거

**Comment by beom-i** [comment]
1. 모든 선생님 정보 조회
<img width="987" alt="스크린샷 2024-02-07 오전 3 55 39" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/61db34ab-ec5e-41ac-9dc0-277640a85c4e">


2. 특정 선생님 정보 조회
<img width="910" alt="스크린샷 2024-02-07 오전 3 55 42" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/ff9cec54-e34a-45ca-b244-30d735e60f2d">


3. 선생님 회원 삭제 (권한 필요)
<img width="941" alt="스크린샷 2024-02-07 오전 3 55 47" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/4ec378a8-86ac-4dbc-812f-0f9e9f787470">


4. 선생님 회원 가입 (권한 필요)
<img width="971" alt="스크린샷 2024-02-07 오전 3 55 49" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/4e55d928-a42a-4686-ab71-6889ce546bbf">



5. 선생님 정보 수정
<img width="1040" alt="스크린샷 2024-02-07 오전 3 57 41" src="https://github.com/NKdevelop1/NK_develop_back/assets/55353401/0f7234a2-c7f5-49e5-9de8-ab4668756e49">

**Comment by DevTae** [comment]
개발 완료된 이슈로 닫겠습니다.
